name: upgrade_util_example
description: Demonstrates how to use the upgrade_util plugin.

publish_to: 'none'

version: 2.3.6+27

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  upgrade_util:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
