name: upgrade_util_example
description: "Demonstrates how to use the upgrade_util plugin."

publish_to: 'none'

version: 2.3.7+29

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  upgrade_util:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
