name: upgrade_util
description: An application upgrade plug-in.
version: 0.1.0
homepage: https://github.com/LiWenHui96/upgrade_util

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  url_launcher_ios: ^6.0.14
  url_launcher_platform_interface: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.upgrade
        pluginClass: UpgradeUtilPlugin
