name: upgrade_util
description: "A plug-in for application upgrades, which implements the method of jumping to the store and the function of installing after downloading the APK."
version: 3.0.0
homepage: https://github.com/LiWenHui96/
repository: https://github.com/LiWenHui96/upgrade_util/
issue_tracker: https://github.com/LiWenHui96/upgrade_util/issues/

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.upgrade
        pluginClass: UpgradeUtilPlugin
      ios:
        pluginClass: UpgradeUtilPlugin
