name: upgrade_util
description: An app upgrade plugin. It realizes the function of jumping to App Store or Market and installing after downloading APK.
version: 0.0.9+1
homepage: https://github.com/LiWenHui96/upgrade_util

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.13+hotfix.7"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.upgrade
        pluginClass: UpgradeUtilPlugin
      ios:
        pluginClass: UpgradeUtilPlugin
