name: upgrade_util
description: A plugin for app upgrades. It can jump to the application store, and implement the function of downloading and installing APK on Android.
version: 2.3.5+1
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/upgrade_util
issue_tracker: https://github.com/LiWenHui96/upgrade_util/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.upgrade
        pluginClass: UpgradeUtilPlugin
      ios:
        pluginClass: UpgradeUtilPlugin
