name: upgrade_util
description: An app upgrade plugin. It realizes the function of jumping to App Store or Market and installing after downloading APK.
version: 2.1.4
homepage: https://github.com/LiWenHui96/upgrade_util

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.upgrade
        pluginClass: UpgradeUtilPlugin
      ios:
        pluginClass: UpgradeUtilPlugin
